apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-time-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-time-service
  template:
    metadata:
      labels:
        app: simple-time-service
    spec:
      containers:
      - name: simple-time-service
        image: ritesh1999/simple-time-service:latest
        ports:
        - containerPort: 3000
