apiVersion: v1
kind: Service
metadata:
  name: simple-time-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: "particle41-rg"
spec:
  type: LoadBalancer
  loadBalancerIP: 172.178.59.11  # Replace with actual LB Public IP once public_ip resource is deplyed from output section
  selector:
    app: simple-time-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
