apiVersion: v1
kind: Service
metadata:
  name: simple-time-service
  labels:
    app: time-service
spec:
  type: ClusterIP  # Internal Service
  selector:
    app: time-service
  ports:
    - protocol: TCP
      port: 3000  # Exposed inside cluster
      targetPort: 3000  # Port inside the container
